apiVersion: v1
kind: Service
metadata:
  name: nagios
  labels:
    heritage: helm
spec:
  type: LoadBalancer
  ports:
  - port: ${LB_PORT}
    targetPort: 80
    protocol: TCP
  selector:
    app: nagios
