.catalog:
  name: Nagios for Glencore
  version: 1.0.0-rancher1
  description: |
    Nagios provides enterprise-class Open Source IT monitoring, network monitoring , server and applications monitoring.
  maintainer: "Stefan Henseler"
  questions:
    - variable: REPLICAS
      default: 1
      min: 1
      max: 10
      label: Server Replicas
      description: Initial number of server replicas
      required: true
      type: int
    - variable: LB_PORT
      default: 80
      label: Server Port
      description: Port to expose the load balancer on
      required: true
      type: int
