apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    heritage: helm
spec:
  type: LoadBalancer
  ports:
  - port: ${LB_PORT}
    targetPort: 8080
    protocol: TCP
  selector:
    app: jenkins
