apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
  labels:
    heritage: helm
spec:
  replicas: ${REPLICAS}
  selector:
    app: jenkins
  template:
    metadata:
      labels:
        heritage: helm
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: "jenkins:latest"
        ports:
        - containerPort: 8080
